- name: Use docker compose to run all containers
  hosts: localhost
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file
      copy:
        src: Hissab-Kitaab-backend/docker-compose.yml
        dest: ./

    - name: Run docker compose up command
      become: true
      ansible_become_pass: Aparna
      docker_compose:
        project_src: ./
        state: present
        pull: yes
