- name: Use docker compose to run all containers
  hosts: localhost
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file
      copy:
        src: Hissab-Kitaab-backend/docker-compose.yml
        dest: ./docker-compose.yml

    - name: Pull latest docker image
      command: docker-compose pull
      args:
        chdir: ./

    - name: Run docker compose up command
      command: docker-compose up -d
      args:
        chdir: ./

